### PR TITLE
Add "VERSION" to output; correct FN input/output; fix failing tests

### PR DESCRIPTION
**Pull request by richardhauer**

### CODE REVIEW

**Comment by bolorundurowb** [comment]
Great work @richardhauer but you didn't add a reference to NetStandard 2.0 which is making the CI build fail. Please do so. Thanks

**Comment by richardhauer** [comment]
.Net Standard is a specification, not a dependency. See https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/.

There is a UI app with unspecified purpose that is built using Mono components in the solution. Those components require .Net Standard 2 lib spec, and I don't think the build server supports that.

There are several more changes I've been making also. The parsers do not follow the RFC at all. Not sure if you want these changes though, as they are pretty dramatic.

I've had to build a tool to import my contacts from Android to Outlook.


Richard Hauer
CTO
PING Works
L 13, 61 Lavender Street, Milsons Point NSW 2061
p: +61 2 9321 1551<tel:+61%202%209321%201551> | www.ping-works.com.au<https://www.ping-works.com.au>
d: +61 2 9321 1556<tel:+61%202%209321%201556> | m: +61 414 189 170<tel:+61%20414%20189%20170>
Download a vCard<https://ping-vcards.azurewebsites.net/api/GenerateVCF?name=richard.hauer>
On 18 Nov 2017, at 4:08 am, Bolorunduro Winner-Timothy B <notifications@github.com<mailto:notifications@github.com>> wrote:


Great work @richardhauer<https://github.com/richardhauer> but you didn't add a reference to NetStandard 2.0 which is making the CI build fail. Please do so. Thanks

**Comment by bolorundurowb** [comment]
@richardhauer about the `vCardCollection` disposal, was the default disposal creating a performance or memory issue or throwing an Exception?

**Comment by richardhauer** [comment]
The issue was when I tried to `::Save()` the image.  The image is based on the underlying data stream, so the `::Save()` method fails if that stream is already disposed.  Best practice for images is to allow the stream that loads the image data to be disposed with the Image itself, rather than manually disposing the stream (even though that is a common pattern).

**Comment by bolorundurowb** [comment]
Hey @richardhauer There have been some changes to the repo. Two things:

1. The UI component has been moved to its own repo so if you could direct your UI related changes to that repo, that would be great, Thanks.

2. I have gone through the changes you requested again and I finally see what you are saying. Please fix the conflicts so I can merge the changes in. Thanks

**Comment by bolorundurowb** [comment]
This has become stale so I'll close this out

**Pull request closed without merging**
