### PR TITLE
Add support for custom telephone types

### PR DESCRIPTION
**Pull request by rallets**
### What does this PR do:
Add support for custom telephone types, as from RFC: (https://datatracker.ietf.org/doc/html/rfc6350#section-6.1.4), see pages 34/35.

### Notes (if any):
Tested with Android Galaxy phone

### CODE REVIEW

**Comment by rallets** [comment]
@bolorundurowb can you take a look to this PR?
I'm not able to reproduce the CI error locally (I'm running Windows), any ideas why it's failing?

**Comment by rallets** [comment]
I found it. I did not pull your latest commits. 
Updating 
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
<PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
```
to
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
<PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
```
breaks the build. 
The change has been introduced with this commit:
(https://github.com/bolorundurowb/vCardLib/commit/532d9ff774a876d0fabf91413bed5affb948a880).
Do you need/want support all these (old) frameworks?

**Comment by bolorundurowb** [comment]
hey @rallets, I'll take a look at the CI as that may need updating

**Comment by bolorundurowb** [comment]
Hey @rallets can you update your branch with the latest `master`? I have changed the appveyor build image and updates the target frameworks

**Comment by rallets** [comment]
@bolorundurowb tks, now the build looks fine!

**Review by bolorundurowb — APPROVED** [review]

**Comment by rallets** [comment]
@bolorundurowb tks!

**Pull request merged**
